version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: referral_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - USE_SQLITE=False
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/referral_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
